### ISSUE TITLE
Navigating with Params

### ISSUE THREAD

**Issue by pereless360** [rwieruch/react-firebase-authentication#2]
Hey Awesome Project! Love the implementation so far just have one question as to how to navigate to other pages programatically with parameters/props?

**Comment by rwieruch** [comment]
If you search for "React Router 4 programmatically change route" you should find something. Basically you have a history object where you can push new routes. 

import { withRouter } from 'react-router-dom'

const ButtonToNavigate = ({ history }) => (
  <button
    type="button"
    onClick={() => history.push('/my-new-location')}
  >
    Navigate
  </button>
);

export default withRouter(ButtonToNavigate);
