### ISSUE TITLE
SignUp page doesn't redirect

### ISSUE THREAD

**Issue by spencexyz** [rwieruch/react-firebase-authentication#6]
`event.preventDefault()` doesn't appear to be working on the SignUp page, which causes the page to refresh and the user is never redirected.

**Comment by rwieruch** [comment]
Hm, I never experienced this nor did anybody else. Why do you think that it doesn't work?

**Comment by spencexyz** [comment]
Hey, thanks for getting back to me. I just realized I changed something in the `doCreateUser` in `db.js`.

When I change it to this:

```
export const doCreateUser = (id, fullname, username, email) => {
  db.ref(`users/${username}`).set({
    fullname,
    email,
  });
}
```

it doesn't work anymore. Do you know why this might be?

**Comment by spencexyz** [comment]
It looks like my addition of `{}`broke it by not returning the promise. Then I get `Can't call setState (or forceUpdate) on an unmounted component.` in the console, which went away when I removed `// this.setState(() => ({ ...INITIAL_STATE }));`. Thanks for the quick response, sorry about opening a bug for something that was user error.

**Comment by rwieruch** [comment]
No worries. Glad that you've figured out the issue :)
